language: ruby
rvm:
  - 2.1.0
gemfile:
  - Gemfile
env:
  - DB=mysql
script:
  - cd matsuri2
  - bundle install --standalone --clean
  - RAILS_ENV=test bundle exec rake --trace db:create
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
